name: setup node

on: workflow_dispatch

jobs:
    setupNode:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
              
            - name: install node js
              uses: actions/setup-node@v6
              with: 
                 node-version: 20

            - name: start the app
              run: npm start

            - name: wait for the application
              run: sleep 5

            - name: exit application
              run: exit 1
              
