name: variables

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Run environment'
        required: true
        default: 'test'
        type: choice
        options:
        - dev
        - prod
        - test

      version:
        description: 'Application version'
        required: true
        default: "v1.0.0"


env:
  TYPE_OF_APP: "1 Tier APP"


jobs:
  show-the-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Display Inputs
        run: |
          echo "Environment: ${{inputs.environment}}"
          echo "Version: ${{inputs.version}}


      - name: Environment Variable
        run: |
          echo "Environment: $env"
