name: Variables-and-secrets-parallel-jobs

on: 
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: variables
        run: echo "My variable created in github ${{secrets.USER}}"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: secrets
        run: echo "My secret for the above variable created in secrets of Github ${{secrets.PASSWORD}}"
      
